### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by teobais** [engagingspaces/vertx-react-example#2]
[![https://gyazo.com/22905d3f193a358931a1d99141255a29](https://i.gyazo.com/22905d3f193a358931a1d99141255a29.png)](https://gyazo.com/22905d3f193a358931a1d99141255a29)

What worked out was changing the maven repo to the standard one:

```
repositories {
        maven {
            url 'https://plugins.gradle.org/m2/'
        }
    }
```

**Comment by aschrijver** [comment]
Thanks for pointing that out and sorry for the late response (no change notifications received by GH). This is fixed in #1
