### ISSUE TITLE
Deployment doesn't start at all

### ISSUE THREAD

**Issue by teobais** [engagingspaces/vertx-react-example#3]
Having waited for quite a while, but nothing happened:
[![https://gyazo.com/e331c816b89faaaf91a693ee8f91d6d2](https://i.gyazo.com/e331c816b89faaaf91a693ee8f91d6d2.png)](https://gyazo.com/e331c816b89faaaf91a693ee8f91d6d2)

**Comment by aschrijver** [comment]
Sorry for the late response (I received no notification from GH on project changes).

Your log indicates the verticle is deployed. It should be available at `http://localhost:8999/web` and will just keep running until you abort it. Nothing fancy will happen :) Now with Apache benchmark use `ab -n 10000 -c150 http://localhost:8999/web`
